import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
const html = await readFile('dist/index.html','utf8');
const base = 'https://www.payload27.com';
assert.equal((html.match(/<h1\b/g)||[]).length,1,'One primary heading');
assert.ok(html.includes(`<link rel="canonical" href="${base}/"`));
assert.ok(html.includes(`content="${base}/social-card.jpg"`));
assert.ok(html.includes('summary_large_image'));
assert.ok(!html.includes('__SOCIAL_IMAGE__') && !html.includes('localhost'));
for (const section of ['lore','mission','token','community']) assert.ok(html.includes(`id="${section}"`));
assert.ok(html.includes('AWAITING LAUNCH'));
assert.ok(!html.includes('BUY $P27'));
assert.ok(html.includes('https://x.com/Payload_27') && html.includes('https://t.me/payload27'));
const schema = JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);
assert.deepEqual(schema['@graph'].map(n=>n['@type']),['Organization','WebSite','WebPage']);
assert.ok((await readFile('dist/robots.txt','utf8')).includes(`${base}/sitemap.xml`));
assert.ok((await readFile('dist/sitemap.xml','utf8')).includes(`<loc>${base}/</loc>`));
await access('dist/social-card.jpg'); await access('dist/favicon.svg');
console.log('SEO checks pass: prerendered content, canonical, sitemap, robots, social card, JSON-LD and prelaunch state.');
